baseURL = 'https://tontonfalls.com/'
languageCode = 'en-us'
title = 'Tonton Falls'

[params]
site_logo = "/images/logo-simple.svg"

[[menu.main]]
name = "À propos"
url = "/about/"
weight = 10

[[menu.main]]
name = "Articles"
url = "/"
weight = 20

[module]
[[module.imports]]
path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"
